
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorI", targetNamespace = "http://jaxws.examples.javacodegeeks.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CalculatorI {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.examples.javacodegeeks.com/CalculatorI/addRequest", output = "http://jaxws.examples.javacodegeeks.com/CalculatorI/addResponse")
    public int add(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.examples.javacodegeeks.com/CalculatorI/divideRequest", output = "http://jaxws.examples.javacodegeeks.com/CalculatorI/divideResponse")
    public int divide(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.examples.javacodegeeks.com/CalculatorI/multiplyRequest", output = "http://jaxws.examples.javacodegeeks.com/CalculatorI/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.examples.javacodegeeks.com/CalculatorI/subtractRequest", output = "http://jaxws.examples.javacodegeeks.com/CalculatorI/subtractResponse")
    public int subtract(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

}
